<wsdl:definitions
     name="insertProducto"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Inventario/InventarioCRUD/insertProducto"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Inventario/InventarioCRUD/insertProducto"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertProducto"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="insertProducto_plt" >
    <plt:role name="insertProducto_role" >
      <plt:portType name="tns:insertProducto_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertProducto" schemaLocation="../Schemas/insertProducto_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="InventarioCollection_msg">
        <wsdl:part name="InventarioCollection" element="top:InventarioCollection"/>
    </wsdl:message>
    <wsdl:portType name="insertProducto_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:InventarioCollection_msg"/>
            <wsdl:output message="tns:InventarioCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
